# analytics.py
from logic import (
    get_user_workouts,
    weekly_summary,
    daily_summary,
    performance_trend,
    average_duration,
)
import plotly.express as px
import pandas as pd


# -----------------------------
# Data Retrieval Functions
# -----------------------------
def user_weekly_summary(user_id):
    """Returns a dict: week_number -> number of workouts"""
    summary = weekly_summary(user_id)
    return {week: count for week, count in summary}


def user_daily_summary(user_id):
    """Returns a dict: date -> number of workouts"""
    summary = daily_summary(user_id)
    return {date: count for date, count in summary}


def user_performance_trend(user_id):
    """Returns previous vs current averages over the last 14 days"""
    return performance_trend(user_id)


def user_average_duration(user_id, last_n_days=7):
    """Returns average workout duration over last_n_days"""
    return average_duration(user_id, last_n_days)


# -----------------------------
# Plotting Functions
# -----------------------------
def plot_weekly_summary(user_id):
    summary = weekly_summary(user_id)
    if not summary:
        return None

    df = pd.DataFrame(summary, columns=["Week", "Workouts"])
    fig = px.bar(df, x="Week", y="Workouts", title="Workouts per Week", text="Workouts")
    fig.update_layout(
        yaxis=dict(dtick=1), xaxis_title="Week Number", yaxis_title="Workout Count"
    )
    return fig


def plot_daily_summary(user_id):
    summary = daily_summary(user_id)
    if not summary:
        return None

    df = pd.DataFrame(summary, columns=["Date", "Workouts"])
    df["Date"] = pd.to_datetime(df["Date"])
    fig = px.line(df, x="Date", y="Workouts", title="Workouts per Day", markers=True)
    fig.update_layout(xaxis_title="Date", yaxis_title="Workout Count")
    return fig


def plot_performance_trend(user_id):
    trend = performance_trend(user_id)
    df = pd.DataFrame(
        {
            "Period": ["Previous", "Current"],
            "Average Duration": [trend["previous"], trend["current"]],
        }
    )
    fig = px.bar(
        df,
        x="Period",
        y="Average Duration",
        title="Performance Trend (Avg Duration)",
        text="Average Duration",
        color="Period",
    )
    fig.update_layout(yaxis_title="Average Duration (minutes)")
    return fig


def plot_activity_trends(user_id):
    """Optional: trends by activity type"""
    workouts = get_user_workouts(user_id)
    if not workouts:
        return None

    # fetch all workouts from logic.py
    from database import DB_PATH
    import sqlite3

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute(
        """
        SELECT date, activity_type, COUNT(*) as count
        FROM WorkoutLog
        WHERE user_id=?
        GROUP BY date, activity_type
        ORDER BY date ASC
    """,
        (user_id,),
    )
    rows = cursor.fetchall()
    conn.close()

    if not rows:
        return None

    df = pd.DataFrame(rows, columns=["Date", "Activity", "Count"])
    df["Date"] = pd.to_datetime(df["Date"])
    fig = px.line(
        df,
        x="Date",
        y="Count",
        color="Activity",
        title="Activity Trends Over Time",
        markers=True,
    )
    fig.update_layout(yaxis_title="Workout Count")
    return fig


# -----------------------------
# Export Charts as PNG
# -----------------------------
def export_chart_as_png(fig, filename="chart.png"):
    img_bytes = fig.to_image(format="png")
    with open(filename, "wb") as f:
        f.write(img_bytes)
    return filename


# -----------------------------
# Export Performance Report as PDF
# -----------------------------
from fpdf import FPDF
import os


def export_performance_pdf(user_id, filename="performance_report.pdf"):
    trend = performance_trend(user_id)

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    pdf.cell(0, 10, "FiTrack Performance Report", ln=True)
    pdf.ln(5)

    pdf.cell(0, 10, f"User ID: {user_id}", ln=True)
    pdf.cell(0, 10, f"Previous Avg Duration: {trend['previous']:.2f} min", ln=True)
    pdf.cell(0, 10, f"Current Avg Duration:  {trend['current']:.2f} min", ln=True)

    pdf.ln(10)
    pdf.cell(0, 10, "Generated by FiTrack", ln=True)

    pdf.output(filename)
    return filename
